name: Publish packages on release

on:
  release:
    types: [unpublished]
#  workflow_dispatch:

permissions:
  contents: write

jobs:
    build_win64:
        name: Build win64 binary
        runs-on: windows-latest
        defaults:
          run:
            shell: bash
        steps:
          - uses: actions/checkout@v4
    
          - uses: actions/setup-python@v5
            with:
              cache: 'pip'
              python-version: '3.12'
    
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install --upgrade cx_Freeze pyperclip toml
    
          - name: Freeze app
            run: cxfreeze bdist_msi
            
          - name: Upload to release
            run: |
                mv dist/*.msi dist/RCAInstaller_win_x64.msi
                gh release upload ${{github.event.release.tag_name}} dist/*.msi
            env:
              GITHUB_TOKEN: ${{ github.TOKEN }}
    build_macarm64:
        name: Build mac arm64 binary
        runs-on: macos-latest
        defaults:
          run:
            shell: bash
        steps:
          - uses: actions/checkout@v4
    
          - uses: actions/setup-python@v5
            with:
              cache: 'pip'
              python-version: '3.12'
    
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install --upgrade cx_Freeze pyperclip toml
    
          - name: Freeze app
            run: cxfreeze bdist_dmg
            
          - name: Upload to release
            run: |
                mv 'build/Robot Coaching Assistant Installer.dmg' 'build/RCAInstaller_mac_arm64.dmg'
                gh release upload ${{github.event.release.tag_name}} 'build/RCAInstaller_mac_arm64.dmg'
            env:
                  GITHUB_TOKEN: ${{ github.TOKEN }}
    build_macx64:
        name: Build mac x64 binary
        runs-on: macos-13
        defaults:
          run:
            shell: bash
        steps:
          - uses: actions/checkout@v4
    
          - uses: actions/setup-python@v5
            with:
              cache: 'pip'
              python-version: '3.12'
    
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install --upgrade cx_Freeze pyperclip toml
    
          - name: Freeze app
            run: cxfreeze bdist_dmg
            
          - name: Upload to release
            run: |
                mv 'build/Robot Coaching Assistant Installer.dmg' 'build/RCAInstaller_mac_x64.dmg'
                gh release upload ${{github.event.release.tag_name}} 'build/RCAInstaller_mac_x64.dmg'
            env:
              GITHUB_TOKEN: ${{ github.TOKEN }}

